language: go
go:
  - 1.7
  - tip
sudo: true
notifications:
   email:
     recipients:
       - team@onionscan.org

install:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get github.com/HouzuoGuo/tiedot
    - go get golang.org/x/crypto/openpgp
    - go get golang.org/x/net/proxy
    - go get golang.org/x/net/html
    - go get github.com/rwcarlsen/goexif/exif
    - go get github.com/rwcarlsen/goexif/tiff
    - go get github.com/s-rah/go-ricochet

script:

    - cd $TRAVIS_BUILD_DIR && ./tests.sh
    - test -z "$GOFMT"
    - goveralls -coverprofile=./coverage.out -service travis-ci
